# Generated by Django 5.2.17 on 2026-09-25 18:12

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('HR', 'HR'), ('MANAGER', 'Manager'), ('FINANCE', 'Finance'), ('SUPPORT', 'Support'), ('EMPLOYEE', 'Employee')], db_index=True, default='EMPLOYEE', max_length=16)),
                ('job_title', models.CharField(blank=True, default='', max_length=120)),
                ('knowledge_scope', models.JSONField(blank=True, default=list)),
                ('agent_scope', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('organization', models.ForeignKey(blank=True, help_text='Null only for the break-glass platform superuser.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['email'],
                'indexes': [models.Index(fields=['organization', 'role'], name='users_organiz_6045b8_idx'), models.Index(fields=['organization', 'department'], name='users_organiz_365bf8_idx'), models.Index(fields=['created_at'], name='users_created_6541e9_idx')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
