# Generated by Django 5.2.17 on 2026-09-25 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/%Y/')),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='enterprise', max_length=16)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('data_region', models.CharField(blank=True, default='', max_length=120)),
                ('mfa_required', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.organization')),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization'], name='departments_organiz_682b86_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='uniq_department_org_name')],
            },
        ),
    ]
